services:
  - type: web
    name: id-extractor-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://blurred-immorally-oaf.ngrok-free.dev
    region: oregon
    plan: free
